### ISSUE TITLE
Missing documentations

### ISSUE THREAD

**Issue by NguyenKhoa2k6** [goldsolitude/config-files#1]
i was new using this, is there any a step-by-step guide where to put at?
![image](https://user-images.githubusercontent.com/100212984/155318009-aed040c9-096f-4ce5-a7de-21c1254f1ce4.png)

**Comment by goldsolitude** [comment]
Hey there, the folders is to use with the app Rainmeter https://www.rainmeter.net . I'll add that to the read-me. Thanks!

**Comment by NguyenKhoa2k6** [comment]
> Hey there, the folders is to use with the app Rainmeter https://www.rainmeter.net (as it is in the folder name). I'll add that to the read-me. Thanks!
> 
> To use those you just drag the individual folders to `C:\Users\YourName\Documents\Rainmeter\Skins` and it should just show up in rainmeter if i recall correctly.

Oh hey, thanks m8 👍
